default_install_hook_types: [pre-commit, pre-push]
repos:
- repo: local
  hooks:
  - id: black
    name: black
    entry: black
    language: system
    files: \.py$
    stages: [pre-commit]
  - id: nixpkgs-fmt
    name: nixpkgs-fmt
    entry: nixpkgs-fmt
    language: system
    files: \.nix$
    stages: [pre-commit]
  - id: editorconfig-checker
    name: editorconfig-checker
    entry: editorconfig-checker
    language: system
    stages: [pre-commit]
